In [2]:
import math

In [3]:
# Calcular la desviacion estandar

alturas = (1.50, 2.20, 1.56, 1.78, 1.82, 1.90, 1.66, 1.91, 1.76, 1.88)

# Calcule la media de los datos
x = sum(alturas)
media = x / 10

print ("La media es:", media)

diferencia_al_cuadrado = ((altura - media) ** 2 for altura in alturas)

suma_de_cuadrado = sum(diferencia_al_cuadrado) / 10

desviacion_estandar = math.sqrt(suma_de_cuadrado)

print ("La suma de los valores menos la medida al cuadrado es:", suma_de_cuadrado)
print ("La desviacion estandar es:", desviacion_estandar)

La media es: 1.797
La suma de los valores menos la medida al cuadrado es: 0.03580099999999999
La desviacion estandar es: 0.18921152184790438


In [4]:
import numpy as np

In [6]:
Dataset = [0.56744433976086, 0.6871979493457484, 0.8463706897561651, 0.31110389619407564, 0.23511891089708503,
           0.6577102252485975, 0.6648803069356928, 0.49989209380778477, 0.023793000481246773, 0.8777416618364761,
           0.45262683262543646, 0.6430419554811486, 0.06347145550399458, 0.10628535246898096, 0.13551828266629173,
           0.7030802149078524, 0.8656176079542628, 0.3939640454664668, 0.5144582885753547, 0.6255032779041944]

#total de datos
total_datos = len(Dataset)
print ("Total de datos:", total_datos)

#media
media = np.mean(Dataset)
print ("La media es:", media)

#mediana
mediana = np.median(Dataset)
print ("La mediana es:", mediana)

#desviacion estandar
desviacion_estandar = np.std(Dataset)
print ("La desviación estándar es:", desviacion_estandar)

#reordenar el arreglo en 5 filas y 4 columnas
reordenar = np.array(Dataset).reshape(5, 4)
print ("El arrelgo reordenado es:\n", reordenar)

#media para la segunda columna
media_segunda_columna = np.mean(reordenar[:, 1])
print ("La media de la segunda columna es:", media_segunda_columna)

#mediana para tercera fila
mediana_tercera_fila = np.median(reordenar[2, :])
print("La mediana de la tercera fila es:", mediana_tercera_fila)

#desviación estándar para los datos de la fila 3 a 5 y las columnas 1 a 3
datos_fila_3_5_columnas_1_3 = reordenar[2:5, 0:3]
desviacion_estandar_fila_3_5_columnas_1_3 = np.std(datos_fila_3_5_columnas_1_3)
print("Desviación estándar para los datos de la fila 3 a 5 y las columnas 1 a 3:", desviacion_estandar_fila_3_5_columnas_1_3)

Total de datos: 20
La media es: 0.49374101939088577
La mediana es: 0.5409513141681073
La desviación estándar es: 0.26357035986903965
El arrelgo reordenado es:
 [[0.56744434 0.68719795 0.84637069 0.3111039 ]
 [0.23511891 0.65771023 0.66488031 0.49989209]
 [0.023793   0.87774166 0.45262683 0.64304196]
 [0.06347146 0.10628535 0.13551828 0.70308021]
 [0.86561761 0.39396405 0.51445829 0.62550328]]
La media de la segunda columna es: 0.5445798468732539
La mediana de la tercera fila es: 0.5478343940532926
Desviación estándar para los datos de la fila 3 a 5 y las columnas 1 a 3: 0.31070966987044213
